### ISSUE TITLE
Nexus 4 Boot Animation not fitting the screen.

### ISSUE THREAD

**Issue by VyronVass** [lichti1901/android_vendor_terminus#1]
Nexus 4 boot animation is not fitting the screen on clean install with 28/30 build.

**Comment by lichti1901** [comment]
Yeah i know. Already fixed here https://github.com/lichti1901/android_vendor_terminus/commit/92dfe3b656c4aacf2811796ecc806226392d4a74

**Comment by VyronVass** [comment]
Thanks for quick response. Great work by the way. Issue closed then.
